title: <p align="center"> Pranav S </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/pranav-saji/">LinkedIn</a> |
  <a href="https://github.com/pranavsaji">GitHub</a>
  
  <br>   
  I'm working on Data Science, Machine learning, Deep Learning & NLP related problems.
  Also handing the Big Data from real-time Ad call data.
  Worked with Deloitte USI
  <br>
  </p>



theme: jekyll-theme-minimal
